### ISSUE TITLE
Option to Set Logger

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/socks5-proxy#3]
Hi there!

People we running into an [issue](https://github.com/cloudfoundry/bosh-deployment-resource/issues/35) where this proxy was printing to stdout breaking the JSON parsing for concourse. A temporary [fix](https://github.com/drich10/socks5-proxy/commit/51188950306377781ed34597a99adbe1981d18ed) has been made which disables the logging. Would y'all be open to a PR allowing users of the library to set the Logger? Just wanted to see what y'all prefer.

**Comment by genevievelesperance** [comment]
We are open to a PR. Thanks @drich10!

**Comment by genevievelesperance** [comment]
This is where the logger would need to go: https://github.com/cloudfoundry/socks5-proxy/blob/master/socks5_proxy.go#L84-L88

The go-socks5 library that this library is using only accepts a logger of type `log.Logger`.

We have opened an issue to make this an interface so that we can control the output a little better here: https://github.com/armon/go-socks5/pull/21
