### ISSUE TITLE
As a user of socks5-proxy, I'd like to configure 'user' from the outside, such that I don't need an account called 'jumpbox' on my system where everyone needs the private key file

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/socks5-proxy#5]
Hey,

how would you feel if we changed https://github.com/cloudfoundry/socks5-proxy/blob/master/socks5_proxy.go#L68 to take in an optional username additionally to the key file?

The reason is: we already have a jumpbox in place, where everyone has a named user and access control is managed by an outside system. It would be cool to be able to use `BOSH_ALL_PROXY` in the CLI and just tunnel on-demand.

wdyt?
/cc @cppforlife

**Comment by cppforlife** [comment]
+1

**Comment by evanfarrar** [comment]
Hey @voelzmo !

We hardcoded this originally because it had a very specific intent (BBL) but if there's interest I am happy to prioritize a change to respect a username value (and already have prioritized it). This will just cover the changes necessary in socks5-proxy though;  I'll close this issue when we have made the change so that you or @cppforlife  could make the dependency bump in the BOSH CLI.
